/**
 * Regenerates .github/ISSUE_TEMPLATE/test-result.yml so its dropdowns list the
 * registered components and the catalog's scenarios. Run after changing
 * participants/ or catalog.json; the "sync" workflow runs it on every push.
 */
import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const ROOT = join(import.meta.dir, "..");
const participants = readdirSync(join(ROOT, "participants"))
  .filter((f) => f.endsWith(".json") && f !== "schema.json")
  .map((f) => JSON.parse(readFileSync(join(ROOT, "participants", f), "utf8")));
const catalog = JSON.parse(readFileSync(join(ROOT, "catalog.json"), "utf8"));

const label = (org: string, c: any) => `${c.name} (${org}, ${c.id})`;
const ehrs = participants.flatMap((p) => p.components.filter((c: any) => c.role === "ehr").map((c: any) => label(p.organization, c)));
const wallets = participants.flatMap((p) =>
  p.components.filter((c: any) => c.role !== "ehr").map((c: any) => label(p.organization, c)),
);
const scenarios = catalog.testCases.map((t: any) => `${t.id} ${t.title}`);
const OTHER = "Other (say which in the note)";
const q = (s: string) => JSON.stringify(s);
const options = (xs: string[], sort = true) => [...(sort ? [...xs].sort((a, b) => a.localeCompare(b, undefined, { numeric: true })) : xs), OTHER].map((x) => `        - ${q(x)}`).join("\n");

const yml = `# Generated by scripts/sync-issue-form.ts from participants/ and catalog.json. Do not edit by hand.
name: Test result
description: Record one test run between an EHR and a wallet.
title: "[result] "
labels: ["result"]
body:
  - type: markdown
    attributes:
      value: >-
        One issue per run. File failures too; discuss them in the comments.
        Close the issue to withdraw the result.
        Scenarios are described at https://smart-health-checkin.org/connectathon/.
  - type: dropdown
    id: scenario
    attributes:
      label: Scenario
      options:
${options(scenarios, false)}
    validations:
      required: true
  - type: dropdown
    id: ehr
    attributes:
      label: EHR
      options:
${options(ehrs)}
    validations:
      required: true
  - type: dropdown
    id: wallet
    attributes:
      label: Wallet
      options:
${options(wallets)}
    validations:
      required: true
  - type: dropdown
    id: path
    attributes:
      label: Path
      options:
        - "web"
        - "native"
    validations:
      required: true
  - type: dropdown
    id: result
    attributes:
      label: Result
      options:
        - "pass"
        - "fail"
        - "blocked"
    validations:
      required: true
  - type: input
    id: device
    attributes:
      label: Device, OS, and browser
      placeholder: "Pixel 8, Android 16, Chrome 141"
  - type: textarea
    id: note
    attributes:
      label: Note
      description: What happened. For a failure, what you expected and what you saw.
  - type: textarea
    id: evidence
    attributes:
      label: Evidence
      description: Paste a testing tool log, or attach screenshots and captured requests and responses.
`;
writeFileSync(join(ROOT, ".github/ISSUE_TEMPLATE/test-result.yml"), yml);
console.log(`test-result.yml: ${scenarios.length} scenarios, ${ehrs.length} EHRs, ${wallets.length} wallets`);
